### ISSUE TITLE
Front-End: Create a Web UI

### ISSUE THREAD

**Issue by WMRamadan** [andersbandt/Financial-Analyzer#14]
Create a Web UI that will consume the back-end api. Each back-end and front-end will be decoupled.

Tasks:

- [x] Choose Framework - chosen. Vue.js
- [ ] Initial UI Skeleton
- [ ] Back-end Integration

**Comment by edwrand** [comment]
Django, Flask, React? I personally like Django but am open to learning a new framework

**Comment by andersbandt** [comment]
> Django, Flask, React? I personally like Django but am open to learning a new framework

what are your thoughts on VueJS? Have been leaning towards that

**Comment by lordlabakdas** [comment]
React is a front end framework written in JavaScript. In the same league as
angular and Vue.

**Comment by lordlabakdas** [comment]
I do not know much about front end development but have heard VueJS is
pretty good for beginners.

The most popular ones are react and angular.

**Comment by edwrand** [comment]
I have not used VueJS (mostly use Django), but I am open to learning it for this project. Is anyone else here already familiar with Vue?

**Comment by lordlabakdas** [comment]
Not sure yet

**Comment by andersbandt** [comment]
The sentiment on the Discord is that people are on board with Vue. Check out the `feature/vue` branch, some work has been done on starting. 

Right now I saw we work on getting a basic skeleton down. I tried for several hours to make multiple pages with a navbar and failed... but I think that would be a good starting place

**Comment by edwrand** [comment]
Ok sounds good. Do you mind resending discord invite?

**Comment by andersbandt** [comment]
> Ok sounds good. Do you mind resending discord invite?

sure --> https://discord.gg/qRKYKUzy
