### ISSUE TITLE
categories/__init__.py has conflicting import * statements

### ISSUE THREAD

**Issue by nate-llc** [andersbandt/Financial-Analyzer#4]
edit: this issue is now on the main branch

i had gotten rid of all of the <code>import *</code> statements, but there is one file which this isn't possible without more discretion and i don't know enough about tkinter to try to make the choice.

in <code>src/categories/__init__.py</code>, there is <code>from tkinter import *</code> and <code>from tkinter.ttk import *</code>. there are three <code>Label</code> objects that are from both of the modules in the <code>Category</code> class method <code>inter_gui</code> below. These <code>Label</code> objects are currently being inherited from <code>tkinter.ttk</code> because that is latest import in the file. so, if what's working now works, we get rid of <code>from tkinter import *</code>. my assumption would to be to do this.

**Comment by andersbandt** [comment]
sounds good. tkinter.ttk is for adding themes to stuff like the Labels. I say get rid of `from tkinter import *`
